### ISSUE TITLE
Traceback (most recent call last)

### ISSUE THREAD

**Issue by itlonewolf** [Jacksgong/okcat#1]
报错信息：

> Traceback (most recent call last):
  File "/Users/xiaoyee/.pyenv/versions/3.5.0/bin/okcat", line 9, in <module>
    load_entry_point('OkCat==1.0.8', 'console_scripts', 'okcat')()
  File "/Users/xiaoyee/.pyenv/versions/3.5.0/lib/python3.5/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/xiaoyee/.pyenv/versions/3.5.0/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/Users/xiaoyee/.pyenv/versions/3.5.0/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/Users/xiaoyee/.pyenv/versions/3.5.0/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/xiaoyee/.pyenv/versions/3.5.0/lib/python3.5/site-packages/okcat/__init__.py", line 35
    print ""
           ^
SyntaxError: Missing parentheses in call to 'print'

如下图：

![image](https://user-images.githubusercontent.com/3354194/30464649-573fdd26-9a05-11e7-9ebe-b01f78c8e463.png)

cus.yml
_只修改了 package_
package: com.sothree.slidinguppanel.demo`

电脑信息：
![image](https://user-images.githubusercontent.com/3354194/30464707-ba7718a0-9a05-11e7-973b-ba834d5b2dee.png)
shou'j
手机信息：
Nexus 5x-Andriod8.0.0
HTC 802w-Andriod5.0.2

**Comment by Jacksgong** [comment]
这是在python 3.0上遇到的BUG，多谢反馈，会尽快修复。

**Comment by Jacksgong** [comment]
已经在1.0.9版本修复，可以通过`sudo pip install okcat --upgrade` 进行升级。
