### ISSUE TITLE
windows error: KeyError: 'HOME'

### ISSUE THREAD

**Issue by liuyunli** [Jacksgong/okcat#13]
PS C:\Users\Administrator\.okcat> okcat.exe -y=demo-config.yml demo-log-file.log
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\Scripts\okcat.exe\__main__.py", line 5, in <module
>
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\okcat\__init__.py", line 21, in
<module>
    from okcat.adb import Adb
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\okcat\adb.py", line 20, in <modu
le>
    from okcat.confloader import ConfLoader
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\okcat\confloader.py", line 22, i
n <module>
    from okcat.helper import handle_home_case, get_conf_path
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\okcat\helper.py", line 31, in <m
odule>
    HOME_PATH = environ['HOME']
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\os.py", line 678, in __getitem__
    raise KeyError(key) from None
KeyError: 'HOME'
PS C:\Users\Administrator\.okcat>

error occur while running in windows 7 OS .Please help to check. thanks

**Comment by xiaominglui** [comment]
在环境变量中增加一项“HOME”，值为实际用户home路径，重启电脑即可生效
