### ISSUE TITLE
用不了啊

### ISSUE THREAD

**Issue by Fearycxy** [Jacksgong/okcat#2]
Traceback (most recent call last):
  File "/usr/local/bin/okcat", line 11, in <module>
    load_entry_point('OkCat==1.0.9', 'console_scripts', 'okcat')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()

**Comment by Jacksgong** [comment]
@Fearycxy 你贴的堆栈并不全，可否贴下完全的堆栈(`return self.resolve()`下面的)？

**Comment by Jacksgong** [comment]
已经修复，可以使用`sudo pip install okcat --upgrade` 升级到1.1.0，谢谢。

**Comment by Fearycxy** [comment]
Traceback (most recent call last):
  File "/usr/local/bin/okcat", line 11, in <module>
    load_entry_point('OkCat==1.1.0', 'console_scripts', 'okcat')()
  File "/usr/local/lib/python3.5/dist-packages/okcat/__init__.py", line 99, in main
    parser.setup(args.yml)
  File "/usr/local/lib/python3.5/dist-packages/okcat/logfile_parser.py", line 43, in setup
    loader.load(get_conf_path(yml_file_name))
  File "/usr/local/lib/python3.5/dist-packages/okcat/helper.py", line 50, in get_conf_path
    if not conf_name.endswith('.yml'):
AttributeError: 'NoneType' object has no attribute 'endswith'
还是不行诶。。大神再看看？
我就okcat接一个log

**Comment by Jacksgong** [comment]
ok，这个原因是因为你没有提供解析日志用的配置文件，解析的配置文件很简单，可以参考下[这里](https://github.com/Jacksgong/okcat/blob/master/README-zh.md)。

可以通过`-y=`来提供配置文件:

```shell
okcat -y=配置文件名 日志文件路径
```

---

这个也确实是BUG，这个将在1.1.1中修复，将这个异常改为一个提示。
