### ISSUE TITLE
运行okcat 包名 会出现以下错误 是怎么回事呢？

### ISSUE THREAD

**Issue by Liloupar** [Jacksgong/okcat#6]
`Traceback (most recent call last):
  File "/usr/local/bin/okcat", line 9, in <module>
    load_entry_point('OkCat==1.1.3', 'console_scripts', 'okcat')()
  File "/Library/Python/2.7/site-packages/okcat/__init__.py", line 102, in main
    _adb.setup(args)
  File "/Library/Python/2.7/site-packages/okcat/adb.py", line 166, in setup
    self.adb = subprocess.Popen(adb_command, stdin=PIPE, stdout=PIPE)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory`

**Comment by Liloupar** [comment]
已找到原因 缺少adb环境变量配置
